#!/usr/bin/env python3
"""Facts for the CodeRabbit routine: one compact JSON digest of every open PR in the six repos.

Structured fields only; CodeRabbit's prose goes out as short excerpts for the model to read,
never matched here, so a rewording cannot mislead it (prismalens/gh-workflows#216).
"""
import json
import re
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

OPERATOR = "Sumit1993"
REPOS = [
    "prismalens/prismalens",
    "prismalens/sreforge",
    "prismalens/gh-workflows",
    "prismalens/prismalens.io",
    "Sumit1993/mage-memory",
    "Sumit1993/rig",
]
CR = "coderabbitai[bot]"
# Every summon names its poster; GitHub shows them all as the operator (Sumit1993/rig#150).
MARKER = "<!-- summoned-by: coderabbit-routine -->"
NOW = datetime.now(timezone.utc)


def request(url, payload=None, method=None):
    # Cloud sessions have no gh CLI; the GitHub proxy swaps the placeholder GH_TOKEN for real credentials.
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "coderabbit-routine"}
    if os.environ.get("GH_TOKEN"):
        headers["Authorization"] = f"Bearer {os.environ['GH_TOKEN']}"
    data = json.dumps(payload).encode() if payload is not None else None
    if data is not None:
        headers["Content-Type"] = "application/json"
    try:
        with urllib.request.urlopen(urllib.request.Request(url, data=data, headers=headers, method=method), timeout=20) as resp:
            return json.load(resp), resp.headers.get("Link") or ""
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"{e.code} {url}: {e.read()[:160]!r}") from None
    except (urllib.error.URLError, TimeoutError) as e:
        raise RuntimeError(f"unreachable {url}: {e}") from None


def gh(path, paginate=False):
    url = f"https://api.github.com/{path}"
    data, link = request(url)
    if not paginate:
        return data
    items = list(data)
    while (m := re.search(r'<([^>]+)>;\s*rel="next"', link)):
        # rel="next" names /repositories/<id>/, which the cloud proxy refuses (#159): keep our path, take its query.
        data, link = request(urllib.parse.urlsplit(url)._replace(query=urllib.parse.urlsplit(m.group(1)).query).geturl())
        items.extend(data)
    return items


def ts(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def age_min(s):
    return int((NOW - ts(s)).total_seconds() // 60)


def excerpt(body, n=400):
    text = re.sub(r"<!--.*?-->", " ", body or "", flags=re.S)
    text = re.sub(r"<[^>]+>|[#>*`|]", " ", text)
    return re.sub(r"\s+", " ", text).strip()[:n]


def summoner(body):
    if MARKER in body:
        return "routine"
    m = re.search(r"<!-- summoned-by: ([\w.-]+)", body)
    if m:
        return m.group(1)
    return "cloud session" if "Generated by [Claude Code]" in body else "unmarked (local session, queue or by hand)"


def login(node):
    return ((node or {}).get("author") or {}).get("login") or ""


def prose(body, n):
    # Script runs and analysis chains sit in <details>; the finding and the verdict sit outside.
    return excerpt(re.sub(r"<details>.*?</details>", " ", body or "", flags=re.S), n)


def coderabbit_threads(repo, n):
    # REST has no resolved flag (GraphQL is refused in cloud sessions), so each thread goes out
    # as its finding, the operator's answer and CodeRabbit's last word, for the model to read.
    comments = gh(f"repos/{repo}/pulls/{n}/comments?per_page=100", paginate=True)
    threads = []
    for root in (c for c in comments if c["user"]["login"] == CR and not c.get("in_reply_to_id")):
        replies = [c for c in comments if c.get("in_reply_to_id") == root["id"]]
        ours = [c for c in replies if c["user"]["login"] == OPERATOR]
        theirs = [c for c in replies if c["user"]["login"] == CR and (not ours or c["created_at"] > ours[-1]["created_at"])]
        threads.append({
            "path": root["path"],
            "commit": root["original_commit_id"][:7],
            "finding": prose(root["body"], 200),
            "operator_reply": ours and prose(ours[-1]["body"], 200) or None,
            "coderabbit_after_reply": theirs and prose(theirs[-1]["body"], 240) or None,
        })
    return threads


def since_review(repo, reviewed, head):
    if not reviewed or reviewed == head:
        return None
    cmp = gh(f"repos/{repo}/compare/{reviewed}...{head}")
    return {
        "commits": [{"sha": c["sha"][:7], "headline": c["commit"]["message"].splitlines()[0]} for c in cmp["commits"]],
        "files": [f"{f['filename']} +{f['additions']} -{f['deletions']}" for f in cmp["files"][:20]],
    }


def pr_facts(repo, pr):
    n = pr["number"]
    author = pr["user"]["login"]
    excluded = None
    if author == "dependabot[bot]":
        excluded = "dependabot"
    elif pr["head"]["ref"].startswith("release-please--"):
        excluded = "release-please"
    elif author != OPERATOR:
        excluded = f"author {author}"
    elif pr["draft"]:
        excluded = "draft"
    if excluded:
        return {"repo": repo, "number": n, "excluded": excluded}

    full = gh(f"repos/{repo}/pulls/{n}")
    head = full["head"]["sha"]
    head_at = gh(f"repos/{repo}/commits/{head}")["commit"]["committer"]["date"]
    files = [f["filename"] for f in gh(f"repos/{repo}/pulls/{n}/files?per_page=100", paginate=True)]
    # A CodeRabbit reply inside a thread is also a review object, with an empty body; it reviews nothing.
    reviews = [
        r for r in gh(f"repos/{repo}/pulls/{n}/reviews?per_page=100", paginate=True)
        if r["user"]["login"] == CR and (r["body"] or "").strip()
    ]
    comments = gh(f"repos/{repo}/issues/{n}/comments?per_page=100", paginate=True)
    cr_comments = [c for c in comments if c["user"]["login"] == CR]
    summons = [
        c for c in comments
        if c["user"]["login"] == OPERATOR and c["body"].lstrip().startswith(("@coderabbitai review", "@coderabbitai full review"))
    ]
    last_summon = summons[-1] if summons else None
    reply = None
    if last_summon:
        after = [c for c in cr_comments if c["created_at"] > last_summon["created_at"]]
        reply = after[0] if after else None

    threads = coderabbit_threads(repo, n)
    return {
        "repo": repo,
        "number": n,
        "title": pr["title"],
        "created_at": pr["created_at"],
        "head": head,
        "head_committed_at": head_at,
        "head_age_min": age_min(head_at),
        "docs_only": bool(files) and full["changed_files"] <= 100
        and all(f.endswith((".md", ".mdx")) or f.startswith("docs/") for f in files),
        "coderabbit_reviewed_head": any(r["commit_id"] == head for r in reviews),
        "coderabbit_last_review_at": reviews[-1]["submitted_at"] if reviews else None,
        "coderabbit_reviews": [
            {"commit": r["commit_id"], "is_head": r["commit_id"] == head, "at": r["submitted_at"], "excerpt": excerpt(r["body"], 160)}
            for r in reviews[-3:]
        ],
        "coderabbit_comments": [
            {"created_at": c["created_at"], "updated_at": c["updated_at"], "excerpt": excerpt(c["body"])}
            for c in cr_comments[-3:]
        ],
        "last_summon": last_summon and {
            "at": last_summon["created_at"],
            "after_head": last_summon["created_at"] > head_at,
            "body": last_summon["body"].strip()[:40],
            "by": summoner(last_summon["body"]),
        },
        "first_coderabbit_reply_after_summon": reply and {"at": reply["created_at"], "excerpt": excerpt(reply["body"])},
        "coderabbit_threads_without_operator_reply": sum(1 for t in threads if not t["operator_reply"]),
        "coderabbit_threads": threads[-6:],
        "since_coderabbit_review": since_review(repo, reviews[-1]["commit_id"] if reviews else None, head),
    }


def last_review_on_closed(repo):
    # A PR closed since its review still holds the hourly window; open PRs alone would miss it.
    closed, page = [], 1
    while True:
        batch = gh(f"repos/{repo}/pulls?state=closed&sort=updated&direction=desc&per_page=50&page={page}")
        recent = [pr for pr in batch if age_min(pr["updated_at"]) <= 120]
        closed += recent
        if len(recent) < len(batch) or len(batch) < 50:
            break
        page += 1
    ats = [
        r["submitted_at"]
        for pr in closed
        for r in gh(f"repos/{repo}/pulls/{pr['number']}/reviews?per_page=100", paginate=True)
        if r["user"]["login"] == CR and (r["body"] or "").strip()
    ]
    return max(ats) if ats else None


def safe_pr_facts(repo, pr):
    # One unreadable PR must not drop its whole repo (#159, prismalens#776).
    try:
        return pr_facts(repo, pr)
    except RuntimeError as e:
        return {"repo": repo, "number": pr["number"], "title": pr["title"], "error": str(e)}


def repo_digest(repo):
    try:
        prs = gh(f"repos/{repo}/pulls?state=open&per_page=100", paginate=True)
        facts = {"pull_requests": [safe_pr_facts(repo, pr) for pr in prs], "closed_last_review_at": last_review_on_closed(repo)}
    except RuntimeError as e:
        facts = {"error": str(e)}
    return repo, facts


def main():
    with ThreadPoolExecutor(len(REPOS)) as pool:
        repos = dict(pool.map(repo_digest, REPOS))
    summons = [
        (p["last_summon"]["at"], f"{p['repo']}#{p['number']}")
        for r in repos.values() for p in r.get("pull_requests", []) if p.get("last_summon")
    ]
    reviewed = [p["coderabbit_last_review_at"] for r in repos.values() for p in r.get("pull_requests", []) if p.get("coderabbit_last_review_at")]
    reviewed += [r["closed_last_review_at"] for r in repos.values() if r.get("closed_last_review_at")]
    last_review = max(reviewed) if reviewed else None
    last = max(summons) if summons else None
    json.dump({
        "now": NOW.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "operator_last_summon": last and {"pr": last[1], "at": last[0], "age_min": age_min(last[0])},
        # CodeRabbit's hourly window runs from the last review it accepted, not from the summon.
        "coderabbit_last_review": last_review and {"at": last_review, "age_min": age_min(last_review)},
        "repos": repos,
    }, sys.stdout, indent=1)
    print()


if __name__ == "__main__":
    main()
